-- Evidencia versionada de autorizaciones y declaraciones de tratamiento de datos.
-- Ejecutar en la base SEIO después de crear la tabla users.
CREATE TABLE IF NOT EXISTS legal_consents (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  subject_user_id INT(11) NOT NULL,
  accepted_by_user_id INT(11) NULL,
  created_by_user_id INT(11) NULL,
  institution VARCHAR(255) NULL,
  subject_type ENUM('adult_student','minor_student','student_unknown','teacher','guardian','other') NOT NULL,
  consent_status ENUM('accepted','pending_guardian','institution_confirmed','revoked') NOT NULL,
  accepter_name VARCHAR(255) NULL,
  accepter_relationship VARCHAR(100) NULL,
  guardian_email VARCHAR(255) NULL,
  guardian_phone VARCHAR(50) NULL,
  policy_version VARCHAR(32) NOT NULL,
  policy_sha256 CHAR(64) NULL,
  purposes JSON NULL,
  acceptance_method VARCHAR(40) NOT NULL DEFAULT 'web_checkbox',
  accepted_at DATETIME NULL,
  revoked_at DATETIME NULL,
  ip_address VARCHAR(45) NULL,
  user_agent VARCHAR(500) NULL,
  notes TEXT NULL,
  notification_status ENUM('pending','sent','partial','failed') NOT NULL DEFAULT 'pending',
  notification_recipients JSON NULL,
  notification_details JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_legal_consents_subject (subject_user_id, created_at),
  INDEX idx_legal_consents_status (consent_status),
  INDEX idx_legal_consents_policy (policy_version),
  CONSTRAINT fk_legal_consents_subject FOREIGN KEY (subject_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_legal_consents_accepter FOREIGN KEY (accepted_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_consents_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
